export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_MESSAGE_SUCCESSED = 'SEND_MESSAGE_SUCCESSED';
export const SEND_MESSAGE_FAILED = 'SEND_MESSAGE_FAILED';

export const SEND_FILE_MESSAGE = 'SEND_FILE_MESSAGE';
export const SEND_FILE_MESSAGE_SUCCESSED = 'SEND_FILE_MESSAGE_SUCCESSED';
export const SEND_FILE_MESSAGE_FAILED = 'SEND_FILE_MESSAGE_FAILED';

export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const DELETE_MESSAGE_SUCCESSED = 'DELETE_MESSAGE_SUCCESSED';
export const DELETE_MESSAGE_FAILED = 'DELETE_MESSAGE_FAILED';

export const EDIT_MESSAGE = 'EDIT_MESSAGE';
export const EDIT_MESSAGE_SUCCESSED = 'EDIT_MESSAGE_SUCCESSED';
export const EDIT_MESSAGE_FAILED = 'EDIT_MESSAGE_FAILED';

export const EDIT_FILE_MESSAGE = 'EDIT_FILE_MESSAGE';
export const EDIT_FILE_MESSAGE_SUCCESSED = 'EDIT_FILE_MESSAGE_SUCCESSED';
export const EDIT_FILE_MESSAGE_FAILED = 'EDIT_FILE_MESSAGE_FAILED';

export const GET_MESSAGES = 'GET_MESSAGES';
export const GET_MESSAGES_SUCCESSED = 'GET_MESSAGES_SUCCESSED';
export const GET_MESSAGES_FAILED = 'GET_MESSAGES_FAILED';

export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED';
export const MESSAGE_UPDATED = 'MESSAGE_UPDATED';
export const MESSAGE_DELETED = 'MESSAGE_DELETED';

export const ON_MESSAGE_TYPING = 'ON_MESSAGE_TYPING';
export const MESSAGE_TYPING_SET = 'MESSAGE_TYPING_SET';
export const MESSAGE_TYPING_ERROR = 'MESSAGE_TYPING_ERROR';

export const MESSAGE_TYPING_END = 'MESSAGE_TYPING_END';

export const USER_TYPING_START = 'USER_TYPING_START';

export const CLEAN_CHAT = 'CLEAN_CHAT';
export const READ_RECEIPT = 'READ_RECEIPT';
export const MARK_AS_READ = 'MARK_AS_READ';

export const PRELOAD_FILE_MESSAGE = 'PRELOAD_FILE_MESSAGE';
export const REPLACE_MESSAGE = 'REPLACE_MESSAGE';

export const CANCEL_UPLOADING = 'CANCEL_UPLOADING';
export const CANCEL_UPLOADING_SUCESSED = 'CANCEL_UPLOADING_SUCESSED';
export const CANCEL_UPLOADING_FAILED = 'CANCEL_UPLOADING_FAILED';
