export const CREATE_OPEN_CHANNEL = 'CREATE_OPEN_CHANNEL';
export const CREATE_OPEN_CHANNEL_SUCCESSED = 'CREATE_OPEN_CHANNEL_SUCCESSED';
export const CREATE_OPEN_CHANNEL_FAILED = 'CREATE_OPEN_CHANNE_FAILEDL';
