export const CREATE_OPEN_CHANNEL = 'CREATE_OPEN_CHANNEL';
export const CREATE_OPEN_CHANNEL_SUCCESSED = 'CREATE_OPEN_CHANNEL_SUCCESSED';
export const CREATE_OPEN_CHANNEL_FAILED = 'CREATE_OPEN_CHANNEL_FAILED';
export const OPEN_CHANNELS_LIST = 'OPEN_CHANNELS_LIST';
export const OPEN_CHANNELS_LIST_SUCCESSED = 'OPEN_CHANNELS_LIST_SUCCESSED';
export const OPEN_CHANNELS_LIST_FAILED = 'OPEN_CHANNELS_LIST_FAILED';
