export const CREATE_GROUP_CHANNEL = 'CREATE_GROUP_CHANNEL';
export const CREATE_GROUP_CHANNEL_SUCCESSED = 'CREATE_GROUP_CHANNEL_SUCCESSED';
export const CREATE_GROUP_CHANNEL_FAILED = 'CREATE_GROUP_CHANNEL_FAILED';
