export const CREATE_OPEN_CHANNEL = 'CREATE_OPEN_CHANNEL';
export const CREATE_OPEN_CHANNEL_SUCCESSED = 'CREATE_OPEN_CHANNEL_SUCCESSED';
export const CREATE_OPEN_CHANNEL_FAILED = 'CREATE_OPEN_CHANNEL_FAILED';

export const OPEN_CHANNELS_LIST = 'OPEN_CHANNELS_LIST';
export const OPEN_CHANNELS_LIST_SUCCESSED = 'OPEN_CHANNELS_LIST_SUCCESSED';
export const OPEN_CHANNELS_LIST_FAILED = 'OPEN_CHANNELS_LIST_FAILED';

export const GET_SELECTED_CHANNEL = 'GET_SELECTED_CHANNEL';
export const GET_SELECTED_CHANNEL_SUCCESSED = 'GET_SELECTED_CHANNEL_SUCCESSED';
export const GET_SELECTED_CHANNEL_FAILED = 'GET_SELECTED_CHANNEL_FAILED';

export const ENTER_CHANNEL = 'ENTER_CHANNEL';
export const ENTER_CHANNEL_SUCCESSED = 'ENTER_CHANNEL_SUCCESSED';
export const ENTER_CHANNEL_FAILED = 'ENTER_CHANNEL_FAILED';

export const LEAVE_CHANNEL = 'LEAVE_CHANNEL';
export const LEAVE_CHANNEL_SUCCESSED = 'LEAVE_CHANNEL_SUCCESSED';
export const LEAVE_CHANNEL_FAILED = 'LEAVE_CHANNEL_FAILED';

export const GET_PARTICIPANTS = 'GET_PARTICIPANTS';
export const GET_PARTICIPANTS_SUCCESSED = 'GET_PARTICIPANTS_SUCCESSED';
export const GET_PARTICIPANTS_FAILED = 'GET_PARTICIPANTS_FAILED';

export const GHANNEL_UPDATED = 'GHANNEL_UPDATED';

export const NEW_USER_ENTERED = 'NEW_USER_ENTERED';

export const USER_EXITED = 'USER_EXITED';

export const UPDATE_PARTICIPANTS_STATUS = 'UPDATE_PARTICIPANTS_STATUS';

export const GET_RECENTLY_MESSAGES = 'GET_RECENTLY_MESSAGES';
export const GET_RECENTLY_MESSAGES_SUCCESSED =
  'GET_RECENTLY_MESSAGES_SUCCESSED';
export const GET_RECENTLY_MESSAGES_FAILED = 'GET_RECENTLY_MESSAGES_FAILED';

export const CREATE_GROUP_CHANNEL = 'CREATE_GROUP_CHANNEL';
export const CREATE_GROUP_CHANNEL_SUCCESSED = 'CREATE_GROUP_CHANNEL_SUCCESSED';
export const CREATE_GROUP_CHANNEL_FAILED = 'CREATE_GROUP_CHANNEL_FAILED';
