export const GET_CHANNEL_LIST = 'GET_CHANNEL_LIST';
export const GET_CHANNEL_LIST_SUCCESSED = 'GET_CHANNEL_LIST_SUCCESSED';
export const GET_CHANNEL_LIST_FAILED = 'GET_CHANNEL_LIST_FAILED';

export const GET_SELECTED_CHANNEL = 'GET_SELECTED_CHANNEL';
export const GET_SELECTED_CHANNEL_SUCCESSED = 'GET_SELECTED_CHANNEL_SUCCESSED';
export const GET_SELECTED_CHANNEL_FAILED = 'GET_SELECTED_CHANNEL_FAILED';

export const INVITE_USERS = 'INVITE_USERS';
export const INVITE_USERS_SUCCESSED = 'INVITE_USERS_SUCCESSED';
export const INVITE_USERS_FAILED = 'INVITE_USERS_FAILED';

export const LEAVE_GROUP = 'LEAVE_GROUP';
export const LEAVE_GROUP_SUCCESSED = 'LEAVE_GROUP_SUCCESSED';
export const LEAVE_GROUP_FAILED = 'LEAVE_GROUP_FAILED';

export const GROUP_UPDATED = 'GROUP_UPDATED';

export const ON_USER_JOINED = 'ON_USER_JOINED';

export const ON_USER_LEFT = 'ON_USER_LEFT';

export const NOTIFICATION_OFF = 'NOTIFICATION_OFF';

export const REFRESHED_MEMBERS = 'REFRESHED_MEMBERS';
export const REFRESH_FAILED = 'REFRESH_FAILED';

export const ON_USER_TYPING = 'ON_USER_TYPING';

export const ON_READ_RECEIPT_UPDATED = 'ON_READ_RECEIPT_UPDATED';

export const CREATE_OPEN_CHANNEL = 'CREATE_OPEN_CHANNEL';
export const CREATE_OPEN_CHANNEL_SUCCESSED = 'CREATE_OPEN_CHANNEL_SUCCESSED';
export const CREATE_OPEN_CHANNEL_FAILED = 'CREATE_OPEN_CHANNEL_FAILED';

export const OPEN_CHANNELS_LIST = 'OPEN_CHANNELS_LIST';
export const OPEN_CHANNELS_LIST_SUCCESSED = 'OPEN_CHANNELS_LIST_SUCCESSED';
export const OPEN_CHANNELS_LIST_FAILED = 'OPEN_CHANNELS_LIST_FAILED';

export const ENTER_CHANNEL = 'ENTER_CHANNEL';
export const ENTER_CHANNEL_SUCCESSED = 'ENTER_CHANNEL_SUCCESSED';
export const ENTER_CHANNEL_FAILED = 'ENTER_CHANNEL_FAILED';

export const LEAVE_CHANNEL = 'LEAVE_CHANNEL';
export const LEAVE_CHANNEL_SUCCESSED = 'LEAVE_CHANNEL_SUCCESSED';
export const LEAVE_CHANNEL_FAILED = 'LEAVE_CHANNEL_FAILED';

export const GET_PARTICIPANTS = 'GET_PARTICIPANTS';
export const GET_PARTICIPANTS_SUCCESSED = 'GET_PARTICIPANTS_SUCCESSED';
export const GET_PARTICIPANTS_FAILED = 'GET_PARTICIPANTS_FAILED';

export const GHANNEL_UPDATED = 'GHANNEL_UPDATED';

export const NEW_USER_ENTERED = 'NEW_USER_ENTERED';

export const USER_EXITED = 'USER_EXITED';

export const UPDATE_PARTICIPANTS_STATUS = 'UPDATE_PARTICIPANTS_STATUS';

export const GET_RECENTLY_MESSAGES = 'GET_RECENTLY_MESSAGES';
export const GET_RECENTLY_MESSAGES_SUCCESSED =
  'GET_RECENTLY_MESSAGES_SUCCESSED';
export const GET_RECENTLY_MESSAGES_FAILED = 'GET_RECENTLY_MESSAGES_FAILED';

export const UPDATE_CHANNEL = 'UPDATE_CHANNEL';
export const UPDATE_CHANNEL_SUCCESSED = 'UPDATE_CHANNEL_SUCCESSED';
export const UPDATE_CHANNEL_FAILED = 'UPDATE_CHANNEL_FAILED';
